---
- name: Create init-pki
  command:
    cmd: "{{ openvpn_easyrsa_tool_path }}/easyrsa init-pki"
    chdir: "{{ openvpn_easy_rsa_path }}"
    creates: "{{ openvpn_easy_rsa_path }}/pki"

- name: Create CA and server certificates
  block:
    - name: Create CA cert & key
      command:
        cmd: "{{ openvpn_easyrsa_tool_path }}/easyrsa build-ca nopass"
        chdir: "{{ openvpn_easy_rsa_path }}"
        creates: "{{ openvpn_easy_rsa_pki_path }}/ca.crt"
      environment:
        EASYRSA_BATCH: "yes"

    - name: Easyrsa build-server-full server nopass
      ansible.builtin.command:
        cmd: "{{ openvpn_easyrsa_tool_path }}/easyrsa build-server-full server nopass"
        chdir: "{{ openvpn_easy_rsa_path }}"
        creates: "{{ openvpn_easy_rsa_pki_path }}/issued/server.crt"
      environment:
        EASYRSA_BATCH: "yes"

    - name: Easyrsa build-client-full client nopass
      ansible.builtin.command:
        cmd: "{{ openvpn_easyrsa_tool_path }}/easyrsa build-client-full client nopass"
        chdir: "{{ openvpn_easy_rsa_path }}"
        creates: "{{ openvpn_easy_rsa_pki_path }}/issued/client.crt"
      environment:
        EASYRSA_BATCH: "yes"

    - name: Create Diffie-Hellman.pem
      command:
        cmd: "{{ openvpn_easyrsa_tool_path }}/easyrsa gen-dh"
        chdir: "{{ openvpn_easy_rsa_path }}"
        creates: "{{ openvpn_easy_rsa_pki_path }}/dh.pem"

    - name: Openvpn --genkey --secret {{ openvpn_easy_rsa_pki_path }}/ta.key
      ansible.builtin.command:
        cmd: "openvpn --genkey --secret {{ openvpn_easy_rsa_pki_path }}/ta.key"
        creates: "{{ openvpn_easy_rsa_pki_path }}/ta.key"

- name: Ensure OpenVpn directory exists
  file:
    path: "{{ openvpn_config_path }}"
    state: directory
    mode: '0755'

- name: Copy file to OpenVPN
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_config_path }}/"
    remote_src: yes
  with_items:
    - "{{ openvpn_easy_rsa_pki_path }}/ca.crt"
    - "{{ openvpn_easy_rsa_pki_path }}/issued/server.crt"
    - "{{ openvpn_easy_rsa_pki_path }}/issued/client.crt"
    - "{{ openvpn_easy_rsa_pki_path }}/private/server.key"
    - "{{ openvpn_easy_rsa_pki_path }}/private/client.key"
    - "{{ openvpn_easy_rsa_pki_path }}/dh.pem"
    - "{{ openvpn_easy_rsa_pki_path }}/ta.key"
